[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tokenbee-sdk"
version = "0.1.0"
authors = [
  { name="TokenBee Inc.", email="hello@tokenbee.dev" },
]
description = "Official Python SDK for TokenBee LLM inference gateway and observability."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "httpx>=0.23.0",
]

